<a href="https://colab.research.google.com/github/sayakpaul/robustness-vit/blob/main/imagenet_results/imagenet_9/ImageNet_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The weights inside `timm` (the library used here for loading the models) were converted from the official model weights mentioned below. 

**Source**:
* BiT: https://tfhub.dev/google/collections/bit/1
* ViT: https://github.com/google-research/vision_transformer/

In [ ]:
!pip install -q timm

     |████████████████████████████████| 296kB 14.7MB/s 


In [ ]:
!git clone https://github.com/MadryLab/backgrounds_challenge

Cloning into 'backgrounds_challenge'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 45 (delta 14), reused 27 (delta 6), pack-reused 0
Unpacking objects: 100% (45/45), done.


In [ ]:
%cd backgrounds_challenge

/content/backgrounds_challenge


In [ ]:
!wget -q https://github.com/MadryLab/backgrounds_challenge/releases/download/data/backgrounds_challenge_data.tar.gz
!tar xf backgrounds_challenge_data.tar.gz

In [ ]:
!python challenge_eval.py -h

usage: challenge_eval.py [-h] [--arch ARCH] [--checkpoint CHECKPOINT]
                         --data-path DATA_PATH [--in9]

optional arguments:
  -h, --help            show this help message and exit
  --arch ARCH           Model architecture, if loading a model checkpoint.
  --checkpoint CHECKPOINT
                        Path to model checkpoint.
  --data-path DATA_PATH
                        Path to the eval data
  --in9                 Enable if the model has 9 output classes, like in IN-9


Before running the scripts below, you would need to ajust them to account for the correct `mean` and `std` (both should be [0.5, 0.5, 0.5]). Also, there may be some problems stemming from flashing data and models to the right device. When that happens simply call `.to()` besides the corresponding variable and set the right device. 

## BiT

In [ ]:
!python challenge_eval.py --model resnetv2_101x3_bitm --data-path bg_challenge

==> Preparing dataset ImageNet9..
At image 0 for class 00_dog, used 0.00 since the last print statement.
Up until now, have 0/0 vulnerable foregrounds.
At image 50 for class 00_dog, used 721.29 since the last print statement.
Up until now, have 43/50 vulnerable foregrounds.
At image 100 for class 00_dog, used 390.73 since the last print statement.
Up until now, have 90/100 vulnerable foregrounds.
At image 150 for class 00_dog, used 405.83 since the last print statement.
Up until now, have 135/150 vulnerable foregrounds.
At image 200 for class 00_dog, used 319.86 since the last print statement.
Up until now, have 181/200 vulnerable foregrounds.
At image 250 for class 00_dog, used 706.28 since the last print statement.
Up until now, have 223/250 vulnerable foregrounds.
At image 300 for class 00_dog, used 573.75 since the last print statement.
Up until now, have 268/300 vulnerable foregrounds.
At image 350 for class 00_dog, used 592.09 since the last print statement.
Up until now, have 31

In [ ]:
!python in9_eval.py --eval-dataset 'original' --model resnetv2_101x3_bitm --data-path bg_challenge

==> Preparing dataset ImageNet9..
100% 507/507 [00:53<00:00,  9.56it/s]
Accuracy on original is 94.32%


In [ ]:
!python in9_eval.py --eval-dataset 'mixed_same' --model resnetv2_101x3_bitm --data-path bg_challenge

==> Preparing dataset ImageNet9..
100% 507/507 [00:53<00:00,  9.54it/s]
Accuracy on mixed_same is 81.19%


In [ ]:
!python in9_eval.py --eval-dataset 'mixed_rand' --model resnetv2_101x3_bitm --data-path bg_challenge

==> Preparing dataset ImageNet9..
100% 507/507 [00:53<00:00,  9.52it/s]
Accuracy on mixed_rand is 76.62%


## ViT

```shell
(base) jupyter@tensorflow24:~/backgrounds_challenge$ python challenge_eval.py --model vit_large_patch16_224 --data-path bg_challenge
==> Preparing dataset ImageNet9..
At image 0 for class 00_dog, used 0.00 since the last print statement.
Up until now, have 0/0 vulnerable foregrounds.
At image 50 for class 00_dog, used 424.84 since the last print statement.
Up until now, have 23/50 vulnerable foregrounds.
At image 100 for class 00_dog, used 348.99 since the last print statement.
Up until now, have 57/100 vulnerable foregrounds.
At image 150 for class 00_dog, used 357.59 since the last print statement.
Up until now, have 87/150 vulnerable foregrounds.
At image 200 for class 00_dog, used 371.92 since the last print statement.
Up until now, have 116/200 vulnerable foregrounds.
At image 250 for class 00_dog, used 383.16 since the last print statement.
Up until now, have 142/250 vulnerable foregrounds.
At image 300 for class 00_dog, used 382.41 since the last print statement.
Up until now, have 169/300 vulnerable foregrounds.
At image 350 for class 00_dog, used 441.94 since the last print statement.
Up until now, have 189/350 vulnerable foregrounds.
At image 400 for class 00_dog, used 385.74 since the last print statement.
Up until now, have 212/400 vulnerable foregrounds.
At image 0 for class 01_bird, used 0.00 since the last print statement.
Up until now, have 238/450 vulnerable foregrounds.
At image 50 for class 01_bird, used 206.51 since the last print statement.
Up until now, have 284/500 vulnerable foregrounds.
At image 100 for class 01_bird, used 107.08 since the last print statement.
Up until now, have 333/550 vulnerable foregrounds.
At image 150 for class 01_bird, used 156.13 since the last print statement.
Up until now, have 380/600 vulnerable foregrounds.
At image 200 for class 01_bird, used 254.28 since the last print statement.
Up until now, have 419/650 vulnerable foregrounds.
At image 250 for class 01_bird, used 198.04 since the last print statement.
Up until now, have 465/700 vulnerable foregrounds.
At image 300 for class 01_bird, used 150.47 since the last print statement.
Up until now, have 513/750 vulnerable foregrounds.
At image 350 for class 01_bird, used 174.16 since the last print statement.
Up until now, have 559/800 vulnerable foregrounds.
At image 400 for class 01_bird, used 173.52 since the last print statement.
Up until now, have 604/850 vulnerable foregrounds.
At image 0 for class 02_wheeled vehicle, used 0.00 since the last print statement.
Up until now, have 651/900 vulnerable foregrounds.
At image 50 for class 02_wheeled vehicle, used 188.95 since the last print statement.
Up until now, have 695/950 vulnerable foregrounds.
At image 100 for class 02_wheeled vehicle, used 217.13 since the last print statement.
Up until now, have 739/1000 vulnerable foregrounds.
At image 150 for class 02_wheeled vehicle, used 295.14 since the last print statement.
Up until now, have 770/1050 vulnerable foregrounds.
At image 200 for class 02_wheeled vehicle, used 175.33 since the last print statement.
Up until now, have 816/1100 vulnerable foregrounds.
At image 250 for class 02_wheeled vehicle, used 207.97 since the last print statement.
Up until now, have 860/1150 vulnerable foregrounds.
At image 300 for class 02_wheeled vehicle, used 153.01 since the last print statement.
Up until now, have 906/1200 vulnerable foregrounds.
At image 350 for class 02_wheeled vehicle, used 129.98 since the last print statement.
Up until now, have 953/1250 vulnerable foregrounds.
At image 400 for class 02_wheeled vehicle, used 197.14 since the last print statement.
Up until now, have 994/1300 vulnerable foregrounds.
At image 0 for class 03_reptile, used 0.00 since the last print statement.
Up until now, have 1043/1350 vulnerable foregrounds.
At image 50 for class 03_reptile, used 249.98 since the last print statement.
Up until now, have 1080/1400 vulnerable foregrounds.
At image 100 for class 03_reptile, used 252.57 since the last print statement.
Up until now, have 1118/1450 vulnerable foregrounds.
At image 150 for class 03_reptile, used 195.30 since the last print statement.
Up until now, have 1159/1500 vulnerable foregrounds.
At image 200 for class 03_reptile, used 186.98 since the last print statement.
Up until now, have 1204/1550 vulnerable foregrounds.
At image 250 for class 03_reptile, used 255.87 since the last print statement.
Up until now, have 1247/1600 vulnerable foregrounds.
At image 300 for class 03_reptile, used 206.11 since the last print statement.
Up until now, have 1289/1650 vulnerable foregrounds.
At image 350 for class 03_reptile, used 190.83 since the last print statement.
Up until now, have 1332/1700 vulnerable foregrounds.
At image 400 for class 03_reptile, used 244.35 since the last print statement.
Up until now, have 1370/1750 vulnerable foregrounds.
At image 0 for class 04_carnivore, used 0.00 since the last print statement.
Up until now, have 1406/1800 vulnerable foregrounds.
At image 50 for class 04_carnivore, used 239.45 since the last print statement.
Up until now, have 1443/1850 vulnerable foregrounds.
At image 100 for class 04_carnivore, used 173.52 since the last print statement.
Up until now, have 1486/1900 vulnerable foregrounds.
At image 150 for class 04_carnivore, used 294.68 since the last print statement.
Up until now, have 1523/1950 vulnerable foregrounds.
At image 200 for class 04_carnivore, used 275.61 since the last print statement.
Up until now, have 1558/2000 vulnerable foregrounds.
At image 250 for class 04_carnivore, used 328.48 since the last print statement.
Up until now, have 1589/2050 vulnerable foregrounds.
At image 300 for class 04_carnivore, used 310.70 since the last print statement.
Up until now, have 1621/2100 vulnerable foregrounds.
At image 350 for class 04_carnivore, used 285.96 since the last print statement.
Up until now, have 1653/2150 vulnerable foregrounds.
At image 400 for class 04_carnivore, used 311.26 since the last print statement.
Up until now, have 1688/2200 vulnerable foregrounds.
At image 0 for class 05_insect, used 0.00 since the last print statement.
Up until now, have 1722/2250 vulnerable foregrounds.
At image 50 for class 05_insect, used 127.48 since the last print statement.
Up until now, have 1769/2300 vulnerable foregrounds.
At image 100 for class 05_insect, used 90.76 since the last print statement.
Up until now, have 1819/2350 vulnerable foregrounds.
At image 150 for class 05_insect, used 115.42 since the last print statement.
Up until now, have 1867/2400 vulnerable foregrounds.
At image 200 for class 05_insect, used 91.27 since the last print statement.
Up until now, have 1917/2450 vulnerable foregrounds.
At image 250 for class 05_insect, used 96.41 since the last print statement.
Up until now, have 1966/2500 vulnerable foregrounds.
At image 300 for class 05_insect, used 109.93 since the last print statement.
Up until now, have 2014/2550 vulnerable foregrounds.
At image 350 for class 05_insect, used 118.48 since the last print statement.
Up until now, have 2063/2600 vulnerable foregrounds.
At image 400 for class 05_insect, used 129.14 since the last print statement.
Up until now, have 2111/2650 vulnerable foregrounds.
At image 150 for class 06_musical instrument, used 123.75 since the last print statement.
Up until now, have 2302/2850 vulnerable foregrounds.
At image 200 for class 06_musical instrument, used 215.24 since the last print statement.
Up until now, have 2343/2900 vulnerable foregrounds.
At image 250 for class 06_musical instrument, used 199.52 since the last print statement.
Up until now, have 2385/2950 vulnerable foregrounds.
At image 300 for class 06_musical instrument, used 152.78 since the last print statement.
Up until now, have 2431/3000 vulnerable foregrounds.
At image 350 for class 06_musical instrument, used 280.11 since the last print statement.
Up until now, have 2469/3050 vulnerable foregrounds.
At image 400 for class 06_musical instrument, used 175.96 since the last print statement.
Up until now, have 2512/3100 vulnerable foregrounds.
At image 0 for class 07_primate, used 0.00 since the last print statement.
Up until now, have 2552/3150 vulnerable foregrounds.
At image 50 for class 07_primate, used 411.45 since the last print statement.
Up until now, have 2576/3200 vulnerable foregrounds.
At image 100 for class 07_primate, used 388.60 since the last print statement.
Up until now, have 2601/3250 vulnerable foregrounds.
At image 150 for class 07_primate, used 319.40 since the last print statement.
Up until now, have 2630/3300 vulnerable foregrounds.
At image 200 for class 07_primate, used 322.67 since the last print statement.
Up until now, have 2664/3350 vulnerable foregrounds.
At image 250 for class 07_primate, used 326.97 since the last print statement.
Up until now, have 2695/3400 vulnerable foregrounds.
At image 300 for class 07_primate, used 355.24 since the last print statement.
Up until now, have 2722/3450 vulnerable foregrounds.
At image 350 for class 07_primate, used 192.03 since the last print statement.
Up until now, have 2765/3500 vulnerable foregrounds.
At image 350 for class 08_fish, used 160.69 since the last print statement.
Up until now, have 3145/3950 vulnerable foregrounds.
At image 400 for class 08_fish, used 113.32 since the last print statement.
Up until now, have 3194/4000 vulnerable foregrounds.
Evaluation complete
Summary: 3239/4050 (79.98%) are vulnerable foregrounds.
```

In [ ]:
!python in9_eval.py --eval-dataset 'original' --model vit_large_patch16_224 --data-path bg_challenge

==> Preparing dataset ImageNet9..
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_vit_large_p16_224-4ee7a4dc.pth" to /root/.cache/torch/hub/checkpoints/jx_vit_large_p16_224-4ee7a4dc.pth
100% 507/507 [00:47<00:00, 10.70it/s]
Accuracy on original is 96.67%


In [ ]:
!python in9_eval.py --eval-dataset 'mixed_same' --model vit_large_patch16_224 --data-path bg_challenge

==> Preparing dataset ImageNet9..
100% 507/507 [00:47<00:00, 10.67it/s]
Accuracy on mixed_same is 88.49%


In [ ]:
!python in9_eval.py --eval-dataset 'mixed_rand' --model vit_large_patch16_224 --data-path bg_challenge

==> Preparing dataset ImageNet9..
100% 507/507 [00:47<00:00, 10.65it/s]
Accuracy on mixed_rand is 81.68%
